# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings

# SEO plugin
title: Mark Arsenault
author: Mark Arsenault
tagline: Software Engineer/Developer
description: I'm Mark, and this is my resume. # Longer description for jekyll-seo-tag

url: "https://spacetrout7.github.io"
baseurl: "/spacetrout7.github.io" # change it according to your repository name

twitter:
  username: 
  card: 

social:
  links:
#    - https://twitter.com/spacetrout7
#    - https://www.facebook.com/spacetrout7
     - https://www.linkedin.com/in/spacetrout7
     - https://github.com/spacetrout7
#    - https://keybase.io/spacetrout7

google_site_verification: # Put your google verification tag here

# End SEO

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: gray # gray blue turquoise green berry red

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
