title: Mark Arsenault
tagline: Full Stack Developer
description: Full Stack Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spacetrout7.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author: Mark Arsenault

twitter:
  username: 
  card: 

social:
  links:
#    - https://twitter.com/mark-arsenault
#    - https://www.facebook.com/mark-arsenault
     - https://www.linkedin.com/in/mark-arsenault
     - https://github.com/mark-arsenault
#    - https://keybase.io/mark-arsenault

google_site_verification: # Put your google verification tag here

# End SEO

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: gray # gray blue turquoise green berry red

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development