title: Mark Arsenault
tagline: Full Stack Developer
description: Full Stack Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://spacetrout7.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author: Mark Arsenault

twitter:
  username: fculpo
  card: summary

social:
  links:
    - https://twitter.com/fculpo
    - https://www.linkedin.com/in/fabienculpo
    - https://github.com/fculpo

google_site_verification: LWLcaTw_1TtT5QgF8F4DuEQiNFsV2sLjovpXyR1XcG8

theme_skin: gray # gray blue turquoise green berry red
remote_theme: fculpo/jekyll-pillar

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


